package edu.ensign.cs335.sorting.player;

import java.util.Arrays;

/**
 * This is the driver class designed simply to execute the sorting algorithms.
 *
 * NOTE: For this assignment, DO NOT change the code in this class.
 * Changing code in this class and submitting will result in a 5 point loss ont the assignment.
 */
public class SortSportsPlayerDriver {

    public static void main(String[] args) {
        new SortSportsPlayerDriver();
    }

    private SortSportsPlayerDriver() {

        SportsPlayer[] sportsPlayers = this.generateSportsPlayers();
        System.out.println("Original Listing:");
        this.displaySportsPlayers(sportsPlayers);

        // Sort the SportsPlayer[] generated by generateSportsPlayers() in the following fashion:
        //  1 - Alphabetically by first name.
        Arrays.sort(sportsPlayers, new SportsPlayerComparator.FirstNameComparator());
        System.out.println("Sorted alphabetically by first name:");
        this.displaySportsPlayers(sportsPlayers);

        //  2 - Alphabetically by last name.
        Arrays.sort(sportsPlayers, new SportsPlayerComparator.LastNameComparator());
        System.out.println("Sorted alphabetically by last name:");
        this.displaySportsPlayers(sportsPlayers);

        //  3 - Alphabetical by last name AND by number.
        System.out.println("Sorted alphabetically by last name and then by number:");
        Arrays.sort(sportsPlayers, new SportsPlayerComparator.LastNameNumberComparator());
        this.displaySportsPlayers(sportsPlayers);


        // REMEMBER: You are NOT allowed to change the original code for SportsPlayer.java nor SportsPlayerName.java.
    }

    private void displaySportsPlayers(SportsPlayer[] sportsPlayers) {
        for (int i = 0; i < sportsPlayers.length; i++) {
            System.out.println("\t" + sportsPlayers[i]);
        }
        System.out.println(" ");
        System.out.println(" ");
    }

    private SportsPlayer[] generateSportsPlayers() {

        SportsPlayerName n1 = new SportsPlayerName("Joe", "Ingles");
        n1.setMiddle("Howarth");
        SportsPlayerName n2 = new SportsPlayerName("Karl", "Malone");
        SportsPlayerName n3 = new SportsPlayerName("John", "Stockton");
        SportsPlayerName n11 = new SportsPlayerName("David", "Stockton");
        SportsPlayerName n4 = new SportsPlayerName("Jordan", "Clarkson");
        SportsPlayerName n5 = new SportsPlayerName("Lauri", "Markkanen");
        n5.setMiddle("Elias");
        SportsPlayerName n6 = new SportsPlayerName("Talon", "Horton-Tucker");
        SportsPlayerName n7 = new SportsPlayerName("Collin", "Sexton");
        SportsPlayerName n8 = new SportsPlayerName("Walker", "Kessler");
        n8.setMiddle("Ross");
        SportsPlayerName n9 = new SportsPlayerName("Ron", "Bird");
        SportsPlayerName n10 = new SportsPlayerName("Larry", "Bird");

        SportsPlayer p1 = new SportsPlayer(n1, "3");
        SportsPlayer p2 = new SportsPlayer(n2, "32");
        SportsPlayer p3 = new SportsPlayer(n3, "12");
        SportsPlayer p11 = new SportsPlayer(n11, "6");
        SportsPlayer p4 = new SportsPlayer(n4, "00");
        SportsPlayer p5 = new SportsPlayer(n5, "23");
        SportsPlayer p6 = new SportsPlayer(n6, "0");
        SportsPlayer p7 = new SportsPlayer(n7, "2");
        SportsPlayer p8 = new SportsPlayer(n8, "24");
        SportsPlayer p9 = new SportsPlayer(n9, "23");
        SportsPlayer p10 = new SportsPlayer(n10, "32");

        return new SportsPlayer[]{p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11};
    }
}